// Dati delle votazioni dal CSV
const votiData = [
    { titolo: "PARTE I - Punto 24 - Proposta (a)", parte: 1, punto: 24, proposta: "a", id_proposta: "24.a", votanti: 847, favorevoli: 809, non_favorevoli: 38 },
    { titolo: "PARTE I - Punto 24 - Proposta (b)", parte: 1, punto: 24, proposta: "b", id_proposta: "24.b", votanti: 846, favorevoli: 773, non_favorevoli: 73 },
    { titolo: "PARTE I - Punto 24 - Proposta (c)", parte: 1, punto: 24, proposta: "c", id_proposta: "24.c", votanti: 845, favorevoli: 734, non_favorevoli: 111 },
    { titolo: "PARTE I - Punto 24 - Proposta (d)", parte: 1, punto: 24, proposta: "d", id_proposta: "24.d", votanti: 844, favorevoli: 822, non_favorevoli: 22 },
    { titolo: "PARTE I - Punto 24 - Proposta (e)", parte: 1, punto: 24, proposta: "e", id_proposta: "24.e", votanti: 847, favorevoli: 778, non_favorevoli: 69 },
    { titolo: "PARTE I - Punto 24 - Proposta (f)", parte: 1, punto: 24, proposta: "f", id_proposta: "24.f", votanti: 845, favorevoli: 810, non_favorevoli: 35 },
    { titolo: "PARTE I - Punto 25 - Proposta (a)", parte: 1, punto: 25, proposta: "a", id_proposta: "25.a", votanti: 844, favorevoli: 821, non_favorevoli: 23 },
    { titolo: "PARTE I - Punto 25 - Proposta (b)", parte: 1, punto: 25, proposta: "b", id_proposta: "25.b", votanti: 842, favorevoli: 808, non_favorevoli: 34 },
    { titolo: "PARTE I - Punto 25 - Proposta (c)", parte: 1, punto: 25, proposta: "c", id_proposta: "25.c", votanti: 841, favorevoli: 801, non_favorevoli: 40 },
    { titolo: "PARTE I - Punto 25 - Proposta (d)", parte: 1, punto: 25, proposta: "d", id_proposta: "25.d", votanti: 840, favorevoli: 804, non_favorevoli: 36 },
    { titolo: "PARTE I - Punto 25 - Proposta (e)", parte: 1, punto: 25, proposta: "e", id_proposta: "25.e", votanti: 844, favorevoli: 828, non_favorevoli: 16 },
    { titolo: "PARTE I - Punto 25 - Proposta (f)", parte: 1, punto: 25, proposta: "f", id_proposta: "25.f", votanti: 843, favorevoli: 807, non_favorevoli: 36 },
    { titolo: "PARTE I - Punto 26 - Proposta (a)", parte: 1, punto: 26, proposta: "a", id_proposta: "26.a", votanti: 843, favorevoli: 810, non_favorevoli: 33 },
    { titolo: "PARTE I - Punto 27 - Proposta (a)", parte: 1, punto: 27, proposta: "a", id_proposta: "27.a", votanti: 842, favorevoli: 809, non_favorevoli: 33 },
    { titolo: "PARTE I - Punto 27 - Proposta (b)", parte: 1, punto: 27, proposta: "b", id_proposta: "27.b", votanti: 841, favorevoli: 810, non_favorevoli: 31 },
    { titolo: "PARTE I - Punto 27 - Proposta (c)", parte: 1, punto: 27, proposta: "c", id_proposta: "27.c", votanti: 840, favorevoli: 817, non_favorevoli: 23 },
    { titolo: "PARTE I - Punto 27 - Proposta (d)", parte: 1, punto: 27, proposta: "d", id_proposta: "27.d", votanti: 840, favorevoli: 805, non_favorevoli: 35 },
    { titolo: "PARTE I - Punto 27 - Proposta (e)", parte: 1, punto: 27, proposta: "e", id_proposta: "27.e", votanti: 827, favorevoli: 682, non_favorevoli: 145, tag: "mediamente controverso" },
    { titolo: "PARTE I - Punto 28 - Proposta (a)", parte: 1, punto: 28, proposta: "a", id_proposta: "28.a", votanti: 835, favorevoli: 731, non_favorevoli: 104 },
    { titolo: "PARTE I - Punto 28 - Proposta (b)", parte: 1, punto: 28, proposta: "b", id_proposta: "28.b", votanti: 836, favorevoli: 766, non_favorevoli: 70 },
    { titolo: "PARTE I - Punto 28 - Proposta (c)", parte: 1, punto: 28, proposta: "c", id_proposta: "28.c", votanti: 839, favorevoli: 789, non_favorevoli: 50 },
    { titolo: "PARTE I - Punto 28 - Proposta (d)", parte: 1, punto: 28, proposta: "d", id_proposta: "28.d", votanti: 832, favorevoli: 758, non_favorevoli: 74 },
    { titolo: "PARTE I - Punto 28 - Proposta (e)", parte: 1, punto: 28, proposta: "e", id_proposta: "28.e", votanti: 830, favorevoli: 786, non_favorevoli: 44 },
    { titolo: "PARTE I - Punto 29 - Proposta (a)", parte: 1, punto: 29, proposta: "a", id_proposta: "29.a", votanti: 831, favorevoli: 748, non_favorevoli: 83 },
    { titolo: "PARTE I - Punto 29 - Proposta (b)", parte: 1, punto: 29, proposta: "b", id_proposta: "29.b", votanti: 830, favorevoli: 794, non_favorevoli: 36 },
    { titolo: "PARTE I - Punto 30 - Proposta (a)", parte: 1, punto: 30, proposta: "a", id_proposta: "30.a", votanti: 835, favorevoli: 791, non_favorevoli: 44 },
    { titolo: "PARTE I - Punto 30 - Proposta (b)", parte: 1, punto: 30, proposta: "b", id_proposta: "30.b", votanti: 835, favorevoli: 789, non_favorevoli: 46 },
    { titolo: "PARTE I - Punto 30 - Proposta (c)", parte: 1, punto: 30, proposta: "c", id_proposta: "30.c", votanti: 826, favorevoli: 672, non_favorevoli: 154, tag: "mediamente controverso" },
    { titolo: "PARTE I - Punto 30 - Proposta (d)", parte: 1, punto: 30, proposta: "d", id_proposta: "30.d", votanti: 822, favorevoli: 637, non_favorevoli: 185, tag: "molto controverso" },
    { titolo: "PARTE I - Punto 30 - Proposta (e)", parte: 1, punto: 30, proposta: "e", id_proposta: "30.e", votanti: 829, favorevoli: 749, non_favorevoli: 80 },
    { titolo: "PARTE I - Punto 31 - Proposta (a)", parte: 1, punto: 31, proposta: "a", id_proposta: "31.a", votanti: 832, favorevoli: 764, non_favorevoli: 68 },
    { titolo: "PARTE I - Punto 31 - Proposta (b)", parte: 1, punto: 31, proposta: "b", id_proposta: "31.b", votanti: 827, favorevoli: 700, non_favorevoli: 127, tag: "mediamente controverso" },
    { titolo: "PARTE I - Punto 31 - Proposta (c)", parte: 1, punto: 31, proposta: "c", id_proposta: "31.c", votanti: 834, favorevoli: 786, non_favorevoli: 48 },
    { titolo: "PARTE I - Punto 31 - Proposta (d)", parte: 1, punto: 31, proposta: "d", id_proposta: "31.d", votanti: 829, favorevoli: 797, non_favorevoli: 32 },
    { titolo: "PARTE I - Punto 32 - Proposta (a)", parte: 1, punto: 32, proposta: "a", id_proposta: "32.a", votanti: 830, favorevoli: 796, non_favorevoli: 34 },
    { titolo: "PARTE I - Punto 32 - Proposta (b)", parte: 1, punto: 32, proposta: "b", id_proposta: "32.b", votanti: 830, favorevoli: 816, non_favorevoli: 14 },
    { titolo: "PARTE I - Punto 32 - Proposta (c)", parte: 1, punto: 32, proposta: "c", id_proposta: "32.c", votanti: 824, favorevoli: 793, non_favorevoli: 31 },
    { titolo: "PARTE I - Punto 33 - Proposta (a)", parte: 1, punto: 33, proposta: "a", id_proposta: "33.a", votanti: 820, favorevoli: 759, non_favorevoli: 61 },
    { titolo: "PARTE I - Punto 33 - Proposta (b)", parte: 1, punto: 33, proposta: "b", id_proposta: "33.b", votanti: 825, favorevoli: 789, non_favorevoli: 36 },
    { titolo: "PARTE I - Punto 34 - Proposta (a)", parte: 1, punto: 34, proposta: "a", id_proposta: "34.a", votanti: 819, favorevoli: 747, non_favorevoli: 72 },
    { titolo: "PARTE I - Punto 34 - Proposta (b)", parte: 1, punto: 34, proposta: "b", id_proposta: "34.b", votanti: 819, favorevoli: 762, non_favorevoli: 57 },
    { titolo: "PARTE I - Punto 34 - Proposta (c)", parte: 1, punto: 34, proposta: "c", id_proposta: "34.c", votanti: 819, favorevoli: 794, non_favorevoli: 25 },
    { titolo: "PARTE I - Punto 36 - Proposta (a)", parte: 1, punto: 36, proposta: "a", id_proposta: "36.a", votanti: 824, favorevoli: 772, non_favorevoli: 52 },
    { titolo: "PARTE I - Punto 36 - Proposta (b)", parte: 1, punto: 36, proposta: "b", id_proposta: "36.b", votanti: 817, favorevoli: 757, non_favorevoli: 60 },
    { titolo: "PARTE I - Punto 36 - Proposta (c)", parte: 1, punto: 36, proposta: "c", id_proposta: "36.c", votanti: 818, favorevoli: 720, non_favorevoli: 98 },
    { titolo: "PARTE I - Punto 36 - Proposta (d)", parte: 1, punto: 36, proposta: "d", id_proposta: "36.d", votanti: 813, favorevoli: 692, non_favorevoli: 121 },
    { titolo: "PARTE I - Punto 36 - Proposta (e)", parte: 1, punto: 36, proposta: "e", id_proposta: "36.e", votanti: 798, favorevoli: 710, non_favorevoli: 88 },
    { titolo: "PARTE I - Punto 38 - Proposta (a)", parte: 1, punto: 38, proposta: "a", id_proposta: "38.a", votanti: 821, favorevoli: 788, non_favorevoli: 33 },
    { titolo: "PARTE I - Punto 38 - Proposta (b)", parte: 1, punto: 38, proposta: "b", id_proposta: "38.b", votanti: 819, favorevoli: 779, non_favorevoli: 40 },
    { titolo: "PARTE I - Punto 38 - Proposta (c)", parte: 1, punto: 38, proposta: "c", id_proposta: "38.c", votanti: 818, favorevoli: 742, non_favorevoli: 76 },
    { titolo: "PARTE I - Punto 39 - Proposta (a)", parte: 1, punto: 39, proposta: "a", id_proposta: "39.a", votanti: 819, favorevoli: 799, non_favorevoli: 20 },
    { titolo: "PARTE I - Punto 39 - Proposta (b)", parte: 1, punto: 39, proposta: "b", id_proposta: "39.b", votanti: 814, favorevoli: 774, non_favorevoli: 40 },
    { titolo: "PARTE I - Punto 39 - Proposta (c)", parte: 1, punto: 39, proposta: "c", id_proposta: "39.c", votanti: 810, favorevoli: 755, non_favorevoli: 55 },
    { titolo: "PARTE I - Punto 39 - Proposta (d)", parte: 1, punto: 39, proposta: "d", id_proposta: "39.d", votanti: 816, favorevoli: 781, non_favorevoli: 35 },
    { titolo: "PARTE I - Punto 39 - Proposta (e)", parte: 1, punto: 39, proposta: "e", id_proposta: "39.e", votanti: 815, favorevoli: 740, non_favorevoli: 75 },
    { titolo: "PARTE II - Punto 44 - Proposta (a)", parte: 2, punto: 44, proposta: "a", id_proposta: "44.a", votanti: 832, favorevoli: 809, non_favorevoli: 23 },
    { titolo: "PARTE II - Punto 44 - Proposta (b)", parte: 2, punto: 44, proposta: "b", id_proposta: "44.b", votanti: 828, favorevoli: 808, non_favorevoli: 20 },
    { titolo: "PARTE II - Punto 45 - Proposta (a)", parte: 2, punto: 45, proposta: "a", id_proposta: "45.a", votanti: 831, favorevoli: 815, non_favorevoli: 16 },
    { titolo: "PARTE II - Punto 45 - Proposta (b)", parte: 2, punto: 45, proposta: "b", id_proposta: "45.b", votanti: 830, favorevoli: 791, non_favorevoli: 39 },
    { titolo: "PARTE II - Punto 46 - Proposta (a)", parte: 2, punto: 46, proposta: "a", id_proposta: "46.a", votanti: 827, favorevoli: 805, non_favorevoli: 22 },
    { titolo: "PARTE II - Punto 46 - Proposta (b)", parte: 2, punto: 46, proposta: "b", id_proposta: "46.b", votanti: 827, favorevoli: 783, non_favorevoli: 44 },
    { titolo: "PARTE II - Punto 47 - Proposta (a)", parte: 2, punto: 47, proposta: "a", id_proposta: "47.a", votanti: 822, favorevoli: 719, non_favorevoli: 103 },
    { titolo: "PARTE II - Punto 47 - Proposta (b)", parte: 2, punto: 47, proposta: "b", id_proposta: "47.b", votanti: 825, favorevoli: 763, non_favorevoli: 62 },
    { titolo: "PARTE II - Punto 48 - Proposta (a)", parte: 2, punto: 48, proposta: "a", id_proposta: "48.a", votanti: 827, favorevoli: 783, non_favorevoli: 44 },
    { titolo: "PARTE II - Punto 48 - Proposta (b)", parte: 2, punto: 48, proposta: "b", id_proposta: "48.b", votanti: 824, favorevoli: 714, non_favorevoli: 110 },
    { titolo: "PARTE II - Punto 49 - Proposta (a)", parte: 2, punto: 49, proposta: "a", id_proposta: "49.a", votanti: 824, favorevoli: 783, non_favorevoli: 41 },
    { titolo: "PARTE II - Punto 49 - Proposta (b)", parte: 2, punto: 49, proposta: "b", id_proposta: "49.b", votanti: 827, favorevoli: 772, non_favorevoli: 55 },
    { titolo: "PARTE II - Punto 50 - Proposta (a)", parte: 2, punto: 50, proposta: "a", id_proposta: "50.a", votanti: 827, favorevoli: 796, non_favorevoli: 31 },
    { titolo: "PARTE II - Punto 50 - Proposta (b)", parte: 2, punto: 50, proposta: "b", id_proposta: "50.b", votanti: 824, favorevoli: 795, non_favorevoli: 29 },
    { titolo: "PARTE II - Punto 51 - Proposta (a)", parte: 2, punto: 51, proposta: "a", id_proposta: "51.a", votanti: 827, favorevoli: 791, non_favorevoli: 36 },
    { titolo: "PARTE II - Punto 52 - Proposta (a)", parte: 2, punto: 52, proposta: "a", id_proposta: "52.a", votanti: 828, favorevoli: 793, non_favorevoli: 35 },
    { titolo: "PARTE II - Punto 52 - Proposta (b)", parte: 2, punto: 52, proposta: "b", id_proposta: "52.b", votanti: 825, favorevoli: 784, non_favorevoli: 41 },
    { titolo: "PARTE II - Punto 53 - Proposta (a)", parte: 2, punto: 53, proposta: "a", id_proposta: "53.a", votanti: 824, favorevoli: 788, non_favorevoli: 36 },
    { titolo: "PARTE II - Punto 53 - Proposta (b)", parte: 2, punto: 53, proposta: "b", id_proposta: "53.b", votanti: 823, favorevoli: 766, non_favorevoli: 57 },
    { titolo: "PARTE II - Punto 54 - Proposta (a)", parte: 2, punto: 54, proposta: "a", id_proposta: "54.a", votanti: 827, favorevoli: 781, non_favorevoli: 46 },
    { titolo: "PARTE II - Punto 54 - Proposta (b)", parte: 2, punto: 54, proposta: "b", id_proposta: "54.b", votanti: 825, favorevoli: 785, non_favorevoli: 40 },
    { titolo: "PARTE II - Punto 54 - Proposta (c)", parte: 2, punto: 54, proposta: "c", id_proposta: "54.c", votanti: 824, favorevoli: 777, non_favorevoli: 47 },
    { titolo: "PARTE II - Punto 55 - Proposta (a)", parte: 2, punto: 55, proposta: "a", id_proposta: "55.a", votanti: 830, favorevoli: 810, non_favorevoli: 20 },
    { titolo: "PARTE II - Punto 55 - Proposta (b)", parte: 2, punto: 55, proposta: "b", id_proposta: "55.b", votanti: 830, favorevoli: 794, non_favorevoli: 36 },
    { titolo: "PARTE II - Punto 55 - Proposta (c)", parte: 2, punto: 55, proposta: "c", id_proposta: "55.c", votanti: 818, favorevoli: 753, non_favorevoli: 65 },
    { titolo: "PARTE II - Punto 56 - Proposta (a)", parte: 2, punto: 56, proposta: "a", id_proposta: "56.a", votanti: 823, favorevoli: 792, non_favorevoli: 31 },
    { titolo: "PARTE II - Punto 56 - Proposta (b)", parte: 2, punto: 56, proposta: "b", id_proposta: "56.b", votanti: 822, favorevoli: 763, non_favorevoli: 59 },
    { titolo: "PARTE II - Punto 56 - Proposta (c)", parte: 2, punto: 56, proposta: "c", id_proposta: "56.c", votanti: 821, favorevoli: 776, non_favorevoli: 45 },
    { titolo: "PARTE II - Punto 57 - Proposta (a)", parte: 2, punto: 57, proposta: "a", id_proposta: "57.a", votanti: 823, favorevoli: 789, non_favorevoli: 34 },
    { titolo: "PARTE II - Punto 58 - Proposta (a)", parte: 2, punto: 58, proposta: "a", id_proposta: "58.a", votanti: 827, favorevoli: 809, non_favorevoli: 18 },
    { titolo: "PARTE II - Punto 59 - Proposta (a)", parte: 2, punto: 59, proposta: "a", id_proposta: "59.a", votanti: 822, favorevoli: 784, non_favorevoli: 38 },
    { titolo: "PARTE II - Punto 59 - Proposta (b)", parte: 2, punto: 59, proposta: "b", id_proposta: "59.b", votanti: 818, favorevoli: 759, non_favorevoli: 59 },
    { titolo: "PARTE II - Punto 60 - Proposta (a)", parte: 2, punto: 60, proposta: "a", id_proposta: "60.a", votanti: 813, favorevoli: 784, non_favorevoli: 29 },
    { titolo: "PARTE II - Punto 61 - Proposta (a)", parte: 2, punto: 61, proposta: "a", id_proposta: "61.a", votanti: 815, favorevoli: 785, non_favorevoli: 30 },
    { titolo: "PARTE II - Punto 61 - Proposta (b)", parte: 2, punto: 61, proposta: "b", id_proposta: "61.b", votanti: 813, favorevoli: 771, non_favorevoli: 42 },
    { titolo: "PARTE II - Punto 61 - Proposta (c)", parte: 2, punto: 61, proposta: "c", id_proposta: "61.c", votanti: 813, favorevoli: 789, non_favorevoli: 24 },
    { titolo: "PARTE III - Punto 68 - Proposta (a)", parte: 3, punto: 68, proposta: "a", id_proposta: "68.a", votanti: 825, favorevoli: 802, non_favorevoli: 23 },
    { titolo: "PARTE III - Punto 68 - Proposta (b)", parte: 3, punto: 68, proposta: "b", id_proposta: "68.b", votanti: 822, favorevoli: 786, non_favorevoli: 36 },
    { titolo: "PARTE III - Punto 68 - Proposta (c)", parte: 3, punto: 68, proposta: "c", id_proposta: "68.c", votanti: 824, favorevoli: 773, non_favorevoli: 51 },
    { titolo: "PARTE III - Punto 68 - Proposta (d)", parte: 3, punto: 68, proposta: "d", id_proposta: "68.d", votanti: 823, favorevoli: 786, non_favorevoli: 37 },
    { titolo: "PARTE III - Punto 69 - Proposta (a)", parte: 3, punto: 69, proposta: "a", id_proposta: "69.a", votanti: 825, favorevoli: 805, non_favorevoli: 20 },
    { titolo: "PARTE III - Punto 69 - Proposta (b)", parte: 3, punto: 69, proposta: "b", id_proposta: "69.b", votanti: 823, favorevoli: 804, non_favorevoli: 19 },
    { titolo: "PARTE III - Punto 69 - Proposta (c)", parte: 3, punto: 69, proposta: "c", id_proposta: "69.c", votanti: 820, favorevoli: 755, non_favorevoli: 65 },
    { titolo: "PARTE III - Punto 69 - Proposta (d)", parte: 3, punto: 69, proposta: "d", id_proposta: "69.d", votanti: 819, favorevoli: 777, non_favorevoli: 42 },
    { titolo: "PARTE III - Punto 69 - Proposta (e)", parte: 3, punto: 69, proposta: "e", id_proposta: "69.e", votanti: 823, favorevoli: 797, non_favorevoli: 26 },
    { titolo: "PARTE III - Punto 69 - Proposta (f)", parte: 3, punto: 69, proposta: "f", id_proposta: "69.f", votanti: 820, favorevoli: 773, non_favorevoli: 47 },
    { titolo: "PARTE III - Punto 69 - Proposta (g)", parte: 3, punto: 69, proposta: "g", id_proposta: "69.g", votanti: 821, favorevoli: 784, non_favorevoli: 37 },
    { titolo: "PARTE III - Punto 69 - Proposta (h)", parte: 3, punto: 69, proposta: "h", id_proposta: "69.h", votanti: 820, favorevoli: 796, non_favorevoli: 24 },
    { titolo: "PARTE III - Punto 70 - Proposta (a)", parte: 3, punto: 70, proposta: "a", id_proposta: "70.a", votanti: 819, favorevoli: 789, non_favorevoli: 30 },
    { titolo: "PARTE III - Punto 70 - Proposta (b)", parte: 3, punto: 70, proposta: "b", id_proposta: "70.b", votanti: 819, favorevoli: 788, non_favorevoli: 31 },
    { titolo: "PARTE III - Punto 70 - Proposta (c)", parte: 3, punto: 70, proposta: "c", id_proposta: "70.c", votanti: 820, favorevoli: 773, non_favorevoli: 47 },
    { titolo: "PARTE III - Punto 71 - Proposta (a)", parte: 3, punto: 71, proposta: "a", id_proposta: "71.a", votanti: 818, favorevoli: 750, non_favorevoli: 68 },
    { titolo: "PARTE III - Punto 71 - Proposta (b)", parte: 3, punto: 71, proposta: "b", id_proposta: "71.b", votanti: 817, favorevoli: 661, non_favorevoli: 156, tag: "mediamente controverso" },
    { titolo: "PARTE III - Punto 71 - Proposta (c)", parte: 3, punto: 71, proposta: "c", id_proposta: "71.c", votanti: 813, favorevoli: 625, non_favorevoli: 188, tag: "molto controverso" },
    { titolo: "PARTE III - Punto 72 - Proposta (a)", parte: 3, punto: 72, proposta: "a", id_proposta: "72.a", votanti: 821, favorevoli: 767, non_favorevoli: 54 },
    { titolo: "PARTE III - Punto 72 - Proposta (b)", parte: 3, punto: 72, proposta: "b", id_proposta: "72.b", votanti: 818, favorevoli: 674, non_favorevoli: 144, tag: "mediamente controverso" },
    { titolo: "PARTE III - Punto 72 - Proposta (c)", parte: 3, punto: 72, proposta: "c", id_proposta: "72.c", votanti: 811, favorevoli: 668, non_favorevoli: 143, tag: "mediamente controverso" },
    { titolo: "PARTE III - Punto 72 - Proposta (d)", parte: 3, punto: 72, proposta: "d", id_proposta: "72.d", votanti: 810, favorevoli: 636, non_favorevoli: 174, tag: "molto controverso" },
    { titolo: "PARTE III - Punto 72 - Proposta (e)", parte: 3, punto: 72, proposta: "e", id_proposta: "72.e", votanti: 808, favorevoli: 759, non_favorevoli: 49 },
    { titolo: "PARTE III - Punto 73 - Proposta (a)", parte: 3, punto: 73, proposta: "a", id_proposta: "73.a", votanti: 813, favorevoli: 781, non_favorevoli: 32 },
    { titolo: "PARTE III - Punto 73 - Proposta (b)", parte: 3, punto: 73, proposta: "b", id_proposta: "73.b", votanti: 813, favorevoli: 775, non_favorevoli: 38 },
    { titolo: "PARTE III - Punto 73 - Proposta (c)", parte: 3, punto: 73, proposta: "c", id_proposta: "73.c", votanti: 810, favorevoli: 781, non_favorevoli: 29 },
    { titolo: "PARTE III - Punto 74 - Proposta (a)", parte: 3, punto: 74, proposta: "a", id_proposta: "74.a", votanti: 813, favorevoli: 798, non_favorevoli: 15 },
    { titolo: "PARTE III - Punto 74 - Proposta (b)", parte: 3, punto: 74, proposta: "b", id_proposta: "74.b", votanti: 816, favorevoli: 761, non_favorevoli: 55 },
    { titolo: "PARTE III - Punto 74 - Proposta (c)", parte: 3, punto: 74, proposta: "c", id_proposta: "74.c", votanti: 815, favorevoli: 781, non_favorevoli: 34 },
    { titolo: "PARTE III - Punto 74 - Proposta (d)", parte: 3, punto: 74, proposta: "d", id_proposta: "74.d", votanti: 810, favorevoli: 794, non_favorevoli: 16 },
    { titolo: "PARTE III - Punto 75 - Proposta (a)", parte: 3, punto: 75, proposta: "a", id_proposta: "75.a", votanti: 806, favorevoli: 734, non_favorevoli: 72 },
    { titolo: "PARTE III - Punto 75 - Proposta (b)", parte: 3, punto: 75, proposta: "b", id_proposta: "75.b", votanti: 801, favorevoli: 714, non_favorevoli: 87 }
];

// Funzione per trovare i dati di voto per un punto specifico
function getVotiByPunto(punto) {
    return votiData.filter(v => v.punto === punto);
}

// Funzione per trovare un singolo voto
function getVoto(punto, proposta) {
    return votiData.find(v => v.punto === punto && v.proposta === proposta);
}
